CREATE UNLOGGED TABLE IF NOT EXISTS latestImage
(
    link TEXT
);

CREATE UNLOGGED TABLE IF NOT EXISTS tweets
(
    id BIGSERIAL PRIMARY KEY,
    tid VARCHAR(20)
);

CREATE UNLOGGED TABLE IF NOT EXISTS maxTID
(
    maxTID VARCHAR(20)
);
